// Public
export const MODIFIERS_FAILURE = 'CATEGORIES_FAILURE';
export const MODIFIERS_REQUEST = 'CATEGORIES_REQUEST';
export const SEARCH_MODIFIERS = 'SEARCH_CATEGORIES';

// Create
export const MODIFIERS_CONFLICT = 'CATEGORIES_CONFLICT';
export const SAVE_MODIFIERS = 'SAVE_CATEGORIES';

// Get
export const GET_MODIFIERS = 'GET_CATEGORIES';
